
package Ventana;

import EDD.MonticuloBinario;
import EDD.NodeDoc;
import EDD.NodeUser;
import EDD.TablaDispersion;
import javax.swing.JOptionPane;

/**
 *
 * Ventana donde se manda a imprir a la impresora
 * 
 * @author Gianfranco Mongiello
 */
public class Impresora extends javax.swing.JFrame {

    /**
     * Creates new form Impresora
     */
    public static MonticuloBinario mb;
    public static TablaDispersion tabla;

    public Impresora(TablaDispersion tabla, MonticuloBinario mb) {
        this.tabla = tabla;
        this.mb = mb;
        initComponents();
                System.out.println(mb==null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        cancelarImp = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        document = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cola.setColumns(20);
        cola.setRows(5);
        jScrollPane1.setViewportView(cola);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, 330));

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IMPRESORA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        imprimir.setText("Imprimir Doc");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });
        jPanel1.add(imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, -1));

        cancelarImp.setText("Cancelar Impresión");
        cancelarImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarImpActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel3.setText("Documento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentActionPerformed(evt);
            }
        });
        jPanel1.add(document, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void documentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        String user = this.usuario.getText();
        int indice = tabla.BuscarUsuario(user);
        if(indice!=-1){
        NodeUser nodo = tabla.usuarios[indice];
        if (nodo != null) {
            NodeDoc nd = nodo.buscarDocumento(document.getText());
            if (nd != null) {
                int s = Reloj.segundos;
                if(nodo.getPrioridad().equals("Alta")){
                    s = s/4;
                }else if(nodo.getPrioridad().equals("Media")){
                    s = s/2;
                }
                
                
                nd.etiquetaDeTiempo = s;
                mb.insertar(nd);
                JOptionPane.showMessageDialog(rootPane, "DOCUMENTO AGREGADO", user, HEIGHT);
            }
        }
        cola.setText(mb.imprimir(""));}
    }//GEN-LAST:event_imprimirActionPerformed

    private void cancelarImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarImpActionPerformed
        String user = this.usuario.getText();
        int indice = tabla.BuscarUsuario(user);
        if(indice!=-1){
        NodeUser u = tabla.usuarios[indice];
        if (u != null) {
            NodeDoc doc = u.buscarDocumento(this.document.getText());
            if (doc != null) {
                doc.etiquetaDeTiempo = 0;
                for (int i = 0; i < this.mb.getSize(); i++) {
                    if (this.mb.heap[i] != null) {
                        this.mb.ajustarHaciaAbajo(i);
                    }}
                JOptionPane.showMessageDialog(rootPane, this.mb.eliminarMinimo().title);   
                    
                }
            cola.setText(mb.imprimir(""));
        }}
    }//GEN-LAST:event_cancelarImpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Ventana1 v = new Ventana1(mb, tabla);
    }//GEN-LAST:event_jButton1ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresora.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresora.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresora.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresora.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Impresora(tabla, mb).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarImp;
    private javax.swing.JTextArea cola;
    private javax.swing.JTextField document;
    private javax.swing.JButton imprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
